#!/usr/bin/env bash

# Exit if Error
set -e

echo "== put-object"

# Check bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename
if [ -z "$2" ]; then
    echo "There needs to be a file name eg. ./bucket my-bucket-name filename"
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2

OBJECT_KEY=$(basename "$FILE_NAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILE_NAME \
--key $OBJECT_KEY
